apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.loft.sh
    chart: vcluster
    targetRevision: 0.20.0
    helm:
      releaseName: team-a
      values: |
        controlPlane:
          statefulSet:
            persistence:
              volumeClaim:
                enabled: true
          service:
            type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: team-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true